/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parmeter Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ParmeterTypes#getInt <em>Int</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ParmeterTypes#getString <em>String</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getParmeterTypes()
 * @model
 * @generated
 */
public interface ParmeterTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getParmeterTypes_Int()
   * @model
   * @generated
   */
  String getInt();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.ParmeterTypes#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getParmeterTypes_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.ParmeterTypes#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // ParmeterTypes
